# Generated by Django 2.1.5 on 2021-01-29 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Simulation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('strategie', models.CharField(choices=[('1', 'One'), ('2', 'Two')], max_length=3)),
                ('von_datum', models.DateField()),
                ('bis_datum', models.DateField()),
            ],
        ),
    ]
