# Generated by Django 3.1.6 on 2021-02-09 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Simulation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ISIN', models.CharField(max_length=50)),
                ('strategie', models.CharField(blank=True, default='default_wert', max_length=255)),
                ('von_datum', models.DateField()),
                ('bis_datum', models.DateField()),
                ('nutzername', models.CharField(max_length=30)),
            ],
        ),
    ]
