# Generated by Django 3.1.6 on 2021-02-10 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulation',
            name='startkapital',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=30),
            preserve_default=False,
        ),
    ]
