# Generated by Django 3.1.6 on 2021-02-24 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0002_simulation_startkapital'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulation',
            name='ISIN',
            field=models.CharField(max_length=12),
        ),
    ]
