# Generated by Django 3.1.6 on 2021-02-24 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0003_auto_20210224_0929'),
    ]

    operations = [
        migrations.RenameField(
            model_name='simulation',
            old_name='ISIN',
            new_name='isin',
        ),
    ]
