# Generated by Django 3.1.6 on 2021-03-15 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regel', '0003_auto_20210304_1747'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regel',
            name='nutzername',
        ),
    ]
