# Generated by Django 3.1.6 on 2021-03-15 10:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regel', '0004_remove_regel_nutzername'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regel',
            name='berechnung_pseudo_code',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(2000)]),
        ),
        migrations.AlterField(
            model_name='regel',
            name='beschreibung',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(1000)]),
        ),
    ]
