# Generated by Django 2.1.5 on 2021-01-29 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategie',
            name='regeln',
            field=models.CharField(max_length=100),
        ),
    ]
