# Generated by Django 3.1.6 on 2021-02-23 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategie', '0002_auto_20210223_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategie',
            name='regeln',
            field=models.CharField(max_length=300),
        ),
    ]
