# Generated by Django 3.1.6 on 2021-03-15 21:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategie', '0003_auto_20210223_1923'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='strategie',
            name='nutzername',
        ),
        migrations.AlterField(
            model_name='strategie',
            name='beschreibung',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(1000)]),
        ),
        migrations.AlterField(
            model_name='strategie',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='strategie',
            name='regeln',
            field=models.CharField(max_length=500),
        ),
    ]
