# Generated by Django 3.1.6 on 2021-02-02 13:01

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategie', '0004_auto_20210202_0254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategie',
            name='regeln',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None),
        ),
    ]
