# Generated by Django 3.1.6 on 2021-02-02 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategie', '0005_auto_20210202_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategie',
            name='regeln',
            field=models.CharField(max_length=100),
        ),
    ]
