# Generated by Django 3.1.6 on 2021-02-09 23:06

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Indikator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('beschreibung', models.TextField()),
                ('code', ckeditor_uploader.fields.RichTextUploadingField()),
                ('nutzername', models.CharField(max_length=30)),
            ],
        ),
    ]
