# Generated by Django 3.1.6 on 2021-02-20 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indikator', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='indikator',
            old_name='code',
            new_name='berechnung_pseudo_code',
        ),
    ]
