# Generated by Django 3.1.6 on 2021-02-20 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indikator', '0002_auto_20210220_2007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indikator',
            name='nutzername',
        ),
        migrations.AddField(
            model_name='indikator',
            name='eigene_skala',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='indikator',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
