# Generated by Django 3.1.6 on 2021-02-20 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indikator', '0003_auto_20210220_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indikator',
            name='berechnung_pseudo_code',
            field=models.TextField(),
        ),
    ]
