# Generated by Django 3.1.6 on 2021-03-15 09:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indikator', '0004_auto_20210220_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indikator',
            name='berechnung_pseudo_code',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(2000)]),
        ),
        migrations.AlterField(
            model_name='indikator',
            name='beschreibung',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(1000)]),
        ),
    ]
